# vim: set ft=yaml.ansible:
---
- name: Ensure bash is installed
  become: true
  ansible.builtin.package:
    name:
      - bash
      - bash-completion
    state: present

- name: "Ensure bash is set as default shell for user '{{ bash_user }}'"
  ansible.builtin.user:
    name: "{{ bash_user }}"
    shell: /bin/bash
