---
- name: "Ensure build dependencies are installed"
  become: yes
  ansible.builtin.package:
    name: "{{ hyprland_dependencies[ansible_distribution] }}"

- name: Checkout repository
  ansible.builtin.git:
    repo: https://github.com/hyprwm/Hyprland.git
    depth: 1
    dest: "{{ hyprland_clone_dir }}/hyprland"
    version: "{{ hyprland_version }}"
  register: clone

- name: Compile
  ansible.builtin.command:
    chdir: "{{ hyprland_clone_dir }}/hyprland"
    cmd: "{{ item }}"
  with_items:
    - "meson _build"
    - "ninja -C _build"
  register: compile

- name: Install
  become: yes
  ansible.builtin.command:
    chdir: "{{ hyprland_clone_dir }}/hyprland"
    cmd: "ninja -C _build install"
  when: compile.changed
