---
- hosts: all

  vars_files:
    - config.yml

  vars:
    configs: "{{ playbook_dir }}/files"

  pre_tasks:
    - name: Update package cache
      become: yes
      community.general.pacman:
        update_cache: yes
      tags: [always]

    - name: Install base 
      ansible.builtin.import_tasks: tasks/base.yml
      tags: [base]

  roles:
    - { role: alacritty, tags: [alacritty, terminals] }
    - { role: aur, tags: [aur] }
    - { role: awesome, tags: [awesome] }
    - { role: kitty, tags: [kitty, terminals] }
    - { role: ranger, tags: [ranger] }
    - { role: sddm, tags: [sddm] }
    - { role: xorg, tags: [xorg] }

    # ---- Services ---- #
    - role: service
      tags: [network]
      vars:
        service_packages:
          - "networkmanager"
          - dnsmasq  # Needed?
          - wpa_supplicant  # Needed?
        service_name: "NetworkManager"
    # ---- Pacman ---- #
    - role: package
      tags: [bash, base]
      vars:
        package_names:
          - bash
          - bash-completion
        package_configs:
          - src: "{{ configs }}/bash/"
            dest: "{{ ansible_user_dir }}/"
    - role: package
      tags: [neovim, editors]
      vars:
        package_names:
          - neovim
          - python-pynvim
          - ripgrep
        package_configs:
          - src: "{{ configs }}/nvim"
    - role: package
      tags: [git, base, tools]
      vars:
        package_names:
          - git
        package_configs:
          - src: "{{ configs }}/git"

  tasks:
    - name: Install fonts
      become: yes
      community.general.pacman:
        name:
          - ttf-hack
          - ttf-fira-code
          - otf-font-awesome
      tags: [fonts]

    - name: Install browsers
      become: yes
      community.general.pacman:
        name:
          - firefox
          - chromium
      tags: [browsers]

