---
# {{{ Globals
window_manager: "awesome"
display_manager: "sddm"
file_manager: "ranger"
display_server: "{{ 'wayland' if window_manager == 'sway' else 'xorg' }} ]"
desktop_environment: ""
editor: "nvim"
shell: "bash"
terminal: "kitty"
theme: "nord"
font: "Fira Code"
lang: "en_US.UTF-8"
locale: "lang?"
timezone: "Europe/Oslo"
browser: firefox
network_manager: "networkmanager"
bluetooth_manager: "bluez"
sound_manager: "pulseaudio"

#TODO - backlight

# }}}

# {{{ Display manager
#sddm_configs: "{{ playbook_dir }}/files/sddm"
# }}}

# {{{ Display server

# TODO: How to map package names between i.e. debian and arch?

#xorg_dependencies:
#  - "xf86-video-intel"

xorg_configs:
  - "{{ playbook_dir }}/files/x/40-libinput.conf"
# }}}

# {{{ File Manager
ranger_name: ranger
ranger_dependencies:
  - dragon  # X11
ranger_configs:
  - "{{ playbook_dir }}/files/ranger"
# }}}

# {{{ Window Manager
sway_dependencies:
  - swaybg
  - swaylock
  - swayidle
  - waybar
  - wofi
  - otf-font-awesome
  - xorg-xwayland
  - wl-clipboard
sway_configs:
  - "{{ playbook_dir }}/files/sway"
  - "{{ playbook_dir }}/files/swaylock"
  - "{{ playbook_dir }}/files/waybar"
  - "{{ playbook_dir }}/files/wofi"

awesome_dependencies:
  #- picom  # Not available in Ubuntu < 20.10
  - compton
  - feh
  - rofi
  - dmenu  # until rofi is implemented
  - i3lock
awesome_configs:
  - "{{ playbook_dir }}/files/awesome"
  #  - "{{ playbook_dir }}/files/rofi"
# }}}

### Arch User Repository (AUR) ###

aur_helper: "paru"
aur_helper_clone_path: "{{ ansible_user_dir }}/projects/git"
aur_packages:
  - "nordic-darker-theme"
  - "dragon-drop"  # for sway
  - "autotiling"  # for sway

########
# Base #
########

base_utilities:
  - bat
  - curl
  - fzf
  - gtk3
  - htop
  - man-db
  - neofetch
  - ripgrep
  - unzip
  - vault
  - wget
base_configs:
  - src: "{{ playbook_dir }}/files/bat"
  - src: "{{ playbook_dir }}/files/gtk-3.0"
  - srC: "{{ playbook_dir }}/files/neofetch" 

# {{{ Python

pip_install_packages:
  - ansible-lint
  - black
  - flake8
  - docker
  - molecule[docker]
  - python-language-server  # Used for LSP in Vim
  - neovim

# }}}

### Terminal emulators ###

alacritty_dependencies: []
alacritty_configs:
  - "{{ playbook_dir }}/files/alacritty"

kitty_dependencies:
  - imagemagick
kitty_configs:
  - "{{ playbook_dir }}/files/kitty"

foot_dependencies: []
foot_configs:
  - "{{ playbook_dir }}/files/foot"

### Virtualization ###

vagrant_plugins:
  - vagrant-disksize
  - vagrant-libvirt

# {{{ Wallpapers
wallpaper_sources:
  - https://github.com/linuxdotexe/nordic-wallpapers
# }}}
