---
#######
# AUR #
#######

aur_helper: "paru"
aur_helper_clone_path: "{{ ansible_user_dir }}/projects/git"
aur_packages:
  - "nordic-wallpapers"
  - "nordic-darker-theme"
  - "autotiling"

##############
# Python/Pip #
##############

pip_install_packages:
  - ansible-lint
  - black
  - flake8
  - docker
  - molecule[docker]
  - python-language-server  # Used for LSP in Vim
  - neovim

##################
# Virtualization #
##################

vagrant_plugins:
  - vagrant-disksize
  - vagrant-libvirt

