---
# {{{ Globals
window_manager: "awesome"
display_manager: "sddm"
file_manager: "ranger"
display_server: "{{ 'wayland' if window_manager == 'sway' else 'xorg' }} ]"
desktop_environment: ""
editor: "nvim"
shell: "bash"
terminal: "kitty"
theme: "nord"
font: "Fira Code"
lang: "en_US.UTF-8"
locale: "lang?"
timezone: "Europe/Oslo"
browser: "firefox"
network_manager: "networkmanager"
bluetooth_manager: "blueman"
sound: "pulseaudio"
gtk_theme: "Nordic"
icon_theme: "Papirus-Dark"

#TODO - backlight

# }}}
# {{{ Display server

# TODO: How to map package names between i.e. debian and arch?

#xorg_dependencies:
#  - "xf86-video-intel"

xorg_configs:
  - "{{ playbook_dir }}/files/xorg/40-libinput.conf"

# }}}
# {{{ Dotfiles
dotfiles_repo: "https://github.com/orjangj/dotfiles.git"
# }}}
# {{{ Window Manager
sway_dependencies:
  - swaybg
  - swaylock
  - swayidle
  - waybar
  - wofi
  - otf-font-awesome
  - xorg-xwayland
  - wl-clipboard

awesome_dependencies:
  #- picom  # Not available in Ubuntu < 20.10
  - compton  # For compositing
  - feh  # For selecting random wallpaper
  - rofi
  - i3lock
  - autorandr
  - lm-sensors # For the temp widget
# }}}
# {{{ AUR

aur_helper: "paru"
aur_helper_clone_path: "{{ ansible_user_dir }}/projects/git"
aur_packages:
  - "nordic-darker-theme"
  - "dragon-drop"  # for sway
  - "autotiling"  # for sway
# }}}
#{{{Base 
base_utilities:
  - bat
  - curl
  - fzf
  - gtk3
  - htop
  - man-db
  - neofetch
  - ripgrep
  - unzip
  - vault
  - wget
  - papirus-icon-theme
  - blueman
# }}}
#{{{Python

pip_install_packages:
  - ansible-lint
  - black
  - flake8
  - docker
  - molecule[docker]
  - python-language-server  # Used for LSP in Vim
  - neovim
  - debugpy
  - pytest
  - pytest-cov

# }}}
# {{{ Terminal emulators

kitty_dependencies:
  - imagemagick

# }}}
# {{{ Editors
nvim_version: "0.8.0"
# }}}
# {{{ Virtualization

vagrant_plugins:
  - vagrant-disksize
  - vagrant-libvirt
# }}}
# {{{ Wallpapers
wallpaper_sources:
  - https://github.com/orjangj/wallpapers
# }}}
