---
# {{{ Globals
username: og
hostname: chronos
window_manager: "qtile"
display_manager: ""  # sddm
file_manager: "ranger"
display_server: "{{ 'wayland' if window_manager == 'sway' else 'xorg' }}"
editor: "neovim"
shell: "bash"
terminal: "kitty"
theme: "nord"
font: "Fira Code"
lang: "en_US.UTF-8"
locale: "lang?"
timezone: "Europe/Oslo"
browser: "firefox"
network_manager: "networkmanager"
bluetooth_manager: "blueman"
sound: "pulseaudio"
gtk_theme: "Nordic"
icon_theme: "Papirus-Dark"
#TODO - backlight

# }}}

# {{{ System
# system_backend: "{{ display_server }}"  # TODO -- x11 or xorg?
system_user_name: "{{ username }}"
system_user_directories:
  - "projects"
  - "notes"
system_hostname: "{{ hostname }}"

# }}}
# {{{ Display server

# TODO: How to map package names between i.e. debian and arch?

#xorg_dependencies:
#  - "xf86-video-intel"

xorg_configs:
  - "{{ playbook_dir }}/files/xorg/40-libinput.conf"
  - "{{ playbook_dir }}/files/xorg/00-keyboard.conf"

# }}}
# {{{ Dotfiles
dotfiles_repo: "https://github.com/orjangj/dotfiles.git"
# }}}
# {{{ Window Manager
awesome_dependencies:
  - picom  # For compositing
  - feh  # For selecting random wallpaper
  - rofi
  - i3lock
  - autorandr

qtile_backend: "x11"
qtile_extra_dependencies:
  - feh

hyprland_version: "v0.26.0"
hyprland_clone_dir: "{{ ansible_user_dir }}/projects/git"

waybar_version: "0.9.19"
waybar_clone_dir: "{{ ansible_user_dir }}/projects/git"

# }}}
#{{{Python

pip_install_packages:
  - ansible-lint
  - black
  - flake8
  - docker
  - molecule[docker]
  - python-language-server  # Used for LSP in Vim
  - neovim
  - debugpy
  - pytest
  - pytest-cov
  - khal
  - autotiling  # sway
  - miniterm

# }}}
# {{{ Terminal emulators

kitty_version: "0.28.1"
kitty_with_optional_dependencies: true

# }}}
# {{{ Editors
neovim_version: "v0.9.0"
neovim_clone_dir: "{{ ansible_user_dir }}/projects/git"
# }}}
# {{{ Virtualization

vagrant_plugins:
  - vagrant-disksize
  - vagrant-libvirt
# }}}
# {{{ Wallpapers
wallpaper_sources:
  - https://github.com/orjangj/wallpapers
# }}}

