---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
  # {{{ Pre-tasks
    - name: Arch - Update package cache
      become: yes
      community.general.pacman:
        update_cache: yes
      tags: [always]
      when: ansible_os_family == 'Archlinux'

    - name: Debian - Update package cache
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3000
      tags: [always]
      when: ansible_os_family == 'Debian'
  # }}}
  roles:
    - { role: system, tags: [system] }
    - { role: xorg, tags: [xorg], when: display_server == 'xorg' or 'xorg' in ansible_run_tags }
    - { role: sddm, tags: [sddm, dm], when: display_manager == 'sddm' or 'sddm' in ansible_run_tags }
    - { role: awesome, tags: [awesome, wm], when: window_manager == 'awesome' or 'awesome' in ansible_run_tags }
    - { role: qtile, tags: [qtile, wm], when: window_manager == 'qtile' or 'qtile' in ansible_run_tags }
    - { role: sway, tags: [sway, wm], when: window_manager == 'sway' or 'sway' in ansible_run_tags }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: alacritty, tags: [alacritty, terminal], when: terminal == 'alacritty' or 'alacritty' in ansible_run_tags }
    - { role: kitty, tags: [kitty, terminal], when: terminal == 'kitty' or 'kitty' in ansible_run_tags }
    - { role: foot, tags: [foot, terminal], when: terminal == 'foot' or 'foot' in ansible_run_tags }
    - { role: neovim, tags: [neovim, editor], when: editor == 'neovim' or 'neovim' in ansible_run_tags }
    #- { role: vscode, tags: [vscode, editor], when: editor == 'vscode' or 'vscode' in ansible_run_tags }
    - { role: wallpaper, tags: [wallpaper] }
    - { role: stylua, tags: [stylua, neovim] }
    - { role: lazygit, tags: [lazygit, neovim] }

    # TODO:
    # - ansible_usr_id/dir vs owner: etc...
    # - Rename repo to "workstation"
    # - fix qtile for wayland -- separate x11 and wayland
    # - pip packages in config.yml
    # - dotfiles: compton --> picom
    # - startx -- bash_profile (or .profile)

  tasks:
    - name: Clone git projects
      ansible.builtin.git:
        repo: "{{ item }}"
        depth: 1
        dest: "{{ ansible_user_dir }}/projects/git/{{ item | basename }}"
      with_items:
        - "https://github.com/orjangj/ansible-collection-editors"
        - "https://github.com/orjangj/ansible-collection-virtualization"
        - "https://github.com/orjangj/cookbook"
        - "https://github.com/orjangj/neotest-ctest"
        - "https://github.com/orjangj/polar.nvim"
      tags: [projects]

    - name: Ensure local fonts directory exists
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_user_dir }}/.local/share/fonts"
      tags: [nerdfonts]

    - name: Install nerdfonts
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/{{ item }}.zip"
        dest: "{{ ansible_user_dir }}/.local/share/fonts"
        remote_src: yes
      with_items:
        #- CascadiaCode
        #- FiraCode
        #- FiraMono
        - Hack
        #- Inconsolata
        #- Iosevka
        #- JetBrainsMono
        #- Noto
        - Ubuntu
        - UbuntuMono
      tags: [nerdfonts]
