# vim: set ft=yaml.ansible:
---
- name: Common Workstation
  gather_facts: false
  hosts: all

  vars_files:
    - vars/packagegroups.yml
    - vars/configs.yml

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - facter
      tags: [always]

    - name: "Ensure package dependencies are installed"
      become: true
      ansible.builtin.package:
        name: "{{ packagegroup[ansible_distribution] + packagegroup.common }}"
        state: present
      tags: [package]

  roles:
    - { role: network, tags: network }
    - { role: bluetooth, tags: bluetooth }
    - { role: audio, tags: audio }
    - { role: bash, tags: bash }
    - { role: libvirt, tags: [libvirt, virtualization] }
    # - { role: locale, tags: locale }
    # - { role: sddm, tags: sddm }
    - { role: neovim, tags: neovim }
    - { role: nerdfonts, tags: nerdfonts }
    - { role: lazygit, tags: lazygit }
    - { role: dotfiles, tags: dotfiles }
    - { role: wallpaper, tags: wallpaper }
    - { role: stylua, tags: stylua }
    - { role: xorg, tags: xorg }
    - { role: themes, tags: themes }
    - { role: hyprland, tags: hyprland, when: ansible_distribution == "Fedora" }
    - { role: waybar, tags: waybar, when: ansible_distribution == "Fedora" }

  tasks:
    - name: Clone personal git projects
      ansible.builtin.git:
        repo: "{{ item }}"
        depth: 1
        dest: "{{ ansible_user_dir }}/projects/git/{{ item | basename | replace('.git', '') }}"
        version: "master"
        update: false
      with_items:
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/ansible-collection-editors.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/ansible-collection-virtualization.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/cookbook.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/neobuild.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/neotest-ctest.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/polar.nvim.git"
      tags: [projects]

  # }}}
