---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
  # {{{ Pre-tasks
    - name: Arch - Update package cache
      become: yes
      community.general.pacman:
        update_cache: yes
      tags: [always]
      when: ansible_os_family == 'Archlinux'

    - name: Debian - Update package cache
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3000
      tags: [always]
      when: ansible_os_family == 'Debian'
  # }}}
  roles:
    - { role: system, tags: [system] }
    - { role: xorg, tags: [xorg], when: display_server == 'xorg' or 'xorg' in ansible_run_tags }
    - { role: sddm, tags: [sddm, dm], when: display_manager == 'sddm' or 'sddm' in ansible_run_tags }
    - { role: awesome, tags: [awesome, wm], when: window_manager == 'awesome' or 'awesome' in ansible_run_tags }
    - { role: qtile, tags: [qtile, wm], when: window_manager == 'qtile' or 'qtile' in ansible_run_tags }
    - { role: sway, tags: [sway, wm], when: window_manager == 'sway' or 'sway' in ansible_run_tags }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: alacritty, tags: [alacritty, terminal], when: terminal == 'alacritty' or 'alacritty' in ansible_run_tags }
    - { role: kitty, tags: [kitty, terminal], when: terminal == 'kitty' or 'kitty' in ansible_run_tags }
    - { role: foot, tags: [foot, terminal], when: terminal == 'foot' or 'foot' in ansible_run_tags }
    - { role: nvim, tags: [nvim, editor], when: editor == 'nvim' or 'nvim' in ansible_run_tags }
    #- { role: vscode, tags: [vscode, editor], when: editor == 'vscode' or 'vscode' in ansible_run_tags }
    - { role: wallpaper, tags: [wallpaper] }
    - { role: stylua, tags: [stylua, nvim] }
    - { role: lazygit, tags: [lazygit, nvim] }
