# vim: set ft=yaml.ansible:
---
- name: Hyprland
  hosts: all

  vars_files:
    - config.yml

  vars:
    #sddm_theme: "{{ playbook_dir }}/files/sddm/Nord"
    #sddm_dependencies:
    #  - plasma-framework
    #  - plasma-integration
    package_dependencies:
      Archlinux:
        - xorg-xwayland
        - imagemagick
        - python
        - python-pip
        - python-setuptools
        - ansible-lint
        - python-black
        - flake8
        - python-docker
        - molecule
        - molecule-plugins
        - python-neovim
        - python-pyserial
        - python-pytest
        - python-pytest-cov
        - fd
        - sof-firmware
        - bluez
        - bluez-utils
        - prettier
      Fedora:
        - xorg-x11-server-Xwayland
        - ImageMagick
        - python3
        - python3-pip
        - python3-setuptools
        - python3-ansible-lint
        - black
        - python3-flake8
        - python3-docker
        - python3-molecule
        - python3-molecule-docker
        - python3-molecule-podman
        - python3-neovim
        - python3-pyserial
        - python3-pytest
        - python3-pytest-cov
        - fd-find
      common:
        - acpi
        - alsa-utils
        - bat
        - brightnessctl
        - btop
        - cargo
        - cmake
        - coreutils
        - curl
        - doxygen
        - dunst
        - firefox
        - flameshot  # Use grim + slurp instead?
        - fzf
        - git
        - grim
        - gzip
        - jq
        - lm_sensors
        - man-db
        - make
        - neofetch
        - npm  # neovim dependency
        - polkit
        - swaybg
        - swaylock
        - swayidle
        - waybar
        - wofi
        - wl-clipboard
        - openssl
        - nnn
        - ripgrep
        - rsync
        - tar
        - tldr
        - tmux
        - tree
        - valgrind
        - vim
        - unzip
        - wget
        - zathura

  # Pre-tasks {{{
  pre_tasks:
    - name: Arch - Update package cache
      become: yes
      community.general.pacman:
        update_cache: yes
      tags: [always]
      when: ansible_os_family == 'Archlinux'

    - name: Fedora - Update package cache
      become: yes
      ansible.builtin.dnf:
        state: present
        update_cache: yes
      tags: [always]
      when: ansible_distribution == 'Fedora'
  # }}}
  # Roles {{{
  roles:
    - { role: hyprland, tags: [hyprland] }
    - { role: sddm, tags: [sddm], when: ansible_distribution == 'Archlinux' }
    - { role: waybar, tags: [waybar], when: ansible_distribution == 'Fedora' }  # Need >=v0.9.19, but Fedora 38 only has 0.9.18
    - { role: kitty, tags: [kitty] }
    - { role: neovim, tags: [neovim] }
    - { role: dotfiles, tags: [dotfiles] }
    - { role: wallpaper, tags: [wallpaper] }
    - { role: stylua, tags: [stylua, neovim] }
    - { role: lazygit, tags: [lazygit, neovim] }
  # }}}
  tasks:
    - name: Install package dependencies
      become: yes
      ansible.builtin.package:
        name: "{{ package_dependencies[ansible_distribution] + package_dependencies.common }}"
      tags: [packages]

    # Use pipx instead of pip (see https://bbs.archlinux.org/viewtopic.php?id=286788)
    #- name: Install python package dependencies
    #  ansible.builtin.pip:
    #    name:
    #      - python3-debugpy
    #      - python3-python-language-server
    #  tags: [python]

    - name: Ensure local fonts directory exists
      ansible.builtin.file:
        state: directory
        mode: "0755"
        path: "{{ ansible_user_dir }}/.local/share/fonts"
      tags: [nerdfonts]

    - name: Install nerdfonts
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/{{ item }}.zip"
        dest: "{{ ansible_user_dir }}/.local/share/fonts"
        remote_src: true
      with_items:
        - FiraCode
        - FiraMono
        - Hack
        - Noto
        - Ubuntu
        - UbuntuMono
      tags: [nerdfonts]

    - name: Ensure local themes directory exists
      ansible.builtin.file:
        state: directory
        mode: "0755"
        path: "{{ ansible_user_dir }}/.themes"
      tags: [gtk]

    - name: Install GTK themes
      ansible.builtin.unarchive:
        src: "{{ item }}"
        dest: "{{ ansible_user_dir }}/.themes"
        remote_src: true
      with_items:
        - "https://github.com/EliverLara/Nordic/releases/download/v2.2.0/Nordic-darker.tar.xz"
      tags: [gtk]

    - name: Clone git projects
      ansible.builtin.git:
        repo: "{{ item }}"
        depth: 1
        dest: "{{ ansible_user_dir }}/projects/git/{{ item | basename }}"
        version: "master"
        update: false
      with_items:
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/ansible-collection-editors.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/ansible-collection-virtualization.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/cookbook.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/neobuild.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/neotest-ctest.git"
        - "{{ 'https://github.com/' if ansible_user_id == 'vagrant' else 'git@github.com:' }}orjangj/polar.nvim.git"
      tags: [projects]
