---
- hosts: all

  vars_files:
    - config.yml

  vars:
    configs: "{{ playbook_dir }}/files"

  pre_tasks:
    - name: Update package cache
      become: yes
      community.general.pacman:
        update_cache: yes
      tags: [always]

    - name: Install base 
      ansible.builtin.import_tasks: tasks/base.yml
      tags: [base]

  # Re-using roles with different parameters allow for more
  # fine-grained control of which roles are executed based
  # on tags
  roles:
    # ---- AUR ---- #
    - role: aur
      tags: [base, aur]
    # ---- Pacman ---- #
    - role: package
      tags: [foot, base, terminals]
      vars:
        package_names:
          - foot
        package_configs:
          - src: "{{ configs }}/foot"
    - role: package
      tags: [kitty, terminals]
      vars:
        package_names:
          - kitty
          - imagemagic
        package_configs:
          - src: "{{ configs }}/kitty"
    - role: package
      tags: [alacritty, terminals]
      vars:
        package_names:
          - alacritty
        package_configs:
          - src: "{{ configs }}/alacritty"
    - role: package
      tags: [fonts, base]
      vars:
        package_names:
          - ttf-hack
          - otf-font-awesome
    - role: package
      tags: [tools]
      vars:
        package_names:
          - bat
          - curl
          - fzf
          - gtk3  # Probably installed as dependency from other packages.
          - htop
          - man-db
          - neofetch
          - ripgrep
          - unzip
          - vault
          - wget
          - wl-clipboard  # Should go into sway dependency?
        package_configs:
          - src: "{{ configs }}/bat"
          - src: "{{ configs }}/gtk-3.0"
          - srC: "{{ configs }}/neofetch"
    - role: package
      tags: [browsers]
      vars:
        package_names:
          - firefox
          - chromium
    - role: package
      tags: [bash, base]
      vars:
        package_names:
          - bash
          - bash-completion
        package_configs:
          - src: "{{ configs }}/bash/"
            dest: "{{ ansible_user_dir }}/"
    - role: package
      tags: [ranger, tools]
      vars:
        package_names:
          - ranger
          - dragon-drop
        package_configs:
          - src: "{{ configs }}/ranger"
    - role: package
      tags: [vim, base, editors]
      vars:
        package_names:
          - vim
    - role: package
      tags: [neovim, editors]
      vars:
        package_names:
          - neovim
          - python-pynvim
          - ripgrep
        package_configs:
          - src: "{{ configs }}/nvim"
    - role: package
      tags: [git, base, tools]
      vars:
        package_names:
          - git
        package_configs:
          - src: "{{ configs }}/git"
    - role: package
      tags: [sway, base, wm]
      vars:
        package_names:
          - sway
          - swaybg
          - swaylock
          - swayidle
          - waybar
          - wofi
          - otf-font-awesome
          - xorg-xwayland
        package_configs:
          - src: "{{ configs }}/sway"
          - src: "{{ configs }}/waybar"
          - src: "{{ configs }}/wofi"
          - src: "{{ configs }}/swaylock"

    # TODO: Include service tasks/roles
    
