---
- hosts: all

  vars_files:
    - config.yml

  roles:
    - { role: aur, tags: [base, aur] }
    - { role: foot, tags: [base, foot] }
    - { role: kitty, tags: [kitty] }

  pre_tasks:
    - name: Update package cache
      become: yes
      community.general.pacman:
        update_cache: yes
      tags: [always]

    - name: Install base 
      ansible.builtin.include_tasks: tasks/base.yml
      tags: [base]

  tasks:
    - name: Install packages
      become: yes
      community.general.pacman:
        name: "{{ item }}"
      with_items:
        - unzip
        - git
        - gpm  # general purpose mouse
        - dmenu
        - intel-ucode
        - firefox
        - chromium
        - ttf-hack
      tags: [base, packages]
      
    - name: Include bash task
      ansible.builtin.include_tasks: tasks/bash.yml
      tags: [bash]

    - name: Include bat task
      ansible.builtin.include_tasks: tasks/bat.yml
      tags: [bat]

    - name: Include git task
      ansible.builtin.include_tasks: tasks/git.yml
      tags: [git]

    - name: Include fonts task
      ansible.builtin.include_tasks: tasks/fonts.yml
      tags: [fonts]

    - name: Include neovim task
      ansible.builtin.include_tasks: tasks/neovim.yml
      tags: [neovim]

    - name: Include sway task
      ansible.builtin.include_tasks: tasks/sway.yml
      tags: [sway]

    - name: Include vault task
      ansible.builtin.include_tasks: tasks/vault.yml
      tags: [vault]

