---
collections:
  - name: https://github.com/orjangj/ansible-collection-virtualization.git
    type: git
    version: master
  - name: orjangj.editors
    version: "1.1.0"

roles:
  - name: geerlingguy.pip

