---
- name: Install xorg server and xinit system
  become: yes
  ansible.builtin.package:
    name: "{{ xorg_packages[ansible_os_family] }}"

# Not sure why these directories are not there by default
- name: Ensure X11 directories exists
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/etc/X11/xorg.conf.d"
    - "/usr/share/xsessions"

- name: Copy configuration files in place
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/X11/xorg.conf.d/"
  loop: "{{ xorg_configs }}"
