renode_dependencies:
  Fedora:
    - mono-complete
    - polkit
    - gtk2
    - screen
    #- uml-utilities  # Does not exist (alternative?)
    - gtk-sharp2
    - glibc-devel
    - gcc
    - python3
    - python3-pip
  Debian:
    - mono-complete
    - policykit-1
    - libgtk2.0-0
    - screen
    - uml-utilities
    - gtk-sharp2
    - libc6-dev
    - gcc
    - python3
    - python3-pip
