---
- name: Ensure dependencies are installed
  become: yes
  ansible.builtin.package:
    name: "{{ lazygit_packages[ansible_distribution] }}"
  register: dependencies

- name: Checkout repository
  ansible.builtin.git:
    repo: https://github.com/jesseduffield/lazygit.git
    depth: 1
    dest: "{{ lazygit_clone_dir }}/lazygit"
    version: "{{ lazygit_version }}"
  register: clone

- name: Compile
  ansible.builtin.command:
    chdir: "{{ lazygit_clone_dir }}/lazygit"
    cmd: "go build"
  register: compile
  when: clone.changed or dependencies.changed

- name: Install
  ansible.builtin.command:
    chdir: "{{ lazygit_clone_dir }}/lazygit"
    cmd: "go install"
  when: compile.changed
