---
- name: Ensure wallpaper download directory exists
  ansible.builtin.file:
    path: "{{ wallpaper_dest }}"
    state: directory

- name: Download wallpaper sources
  ansible.builtin.git:
    repo: "{{ item }}"
    depth: 1
    dest: "{{ wallpaper_dest }}/{{ item | basename }}"
  with_items: "{{ wallpaper_sources }}"
