---
- name: "base : Ensure base packages are installed"
  become: yes
  community.general.pacman:
    state: present
    name: "{{ item }}"
  with_items:
    - base
    - base-devel
    - linux
    - linux-firmware
    - linux-headers
    - intel-ucode  # Is this necessary?
    - git
    - python3
    - vim

- name: "base : Ensure networking packages are installed"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  with_items:
    - networkmanager
    - network-manager-applet
    - avahi
    - openssh
    - bluez
    - bluez-utils
    - dnsmasq  # Needed?
    - wpa_supplicant  # Needed?

- name: "base : Ensure audio packages are installed"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  with_items:
    - pulseaudio  # vs pipewire?
    - sof-firmware

- name: "base : Ensure display packages are installed"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  with_items:
    - brightnessctl

- name: "base : Ensure video/gpu packages are installed"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  with_items:
    - mesa
    - mesa-utils

- name: "base : Ensure security packages are installed"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  with_items:
    - firewalld

- name: "base : Add {{ ansible_env.USER }} user to selected groups"
  become: yes
  ansible.builtin.user:
    user: "{{ ansible_env.USER }}"
    groups: "{{ item }}"
    append: yes
  with_items:
    - adm
    - wheel
    - video
