- name: "sway : Ensure Sway is installed"
  become: yes
  ansible.builtin.package:
    name: sway
  tags: [sway]

- name: "sway : Copy sway configuration in place"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/sway"
    dest: "{{ ansible_user_dir }}/.config"
  tags: [sway]

- name: "sway : Ensure additional dependencies are installed"
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
  with_items:
    - swaybg
    - swaylock
    - swayidle
    - waybar
    - wofi
    - otf-font-awesome
    - xorg-xwayland
  tags: [sway]

- name: "sway : Copy additional configurations in place"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config"
  with_items:
    - "{{ playbook_dir }}/files/waybar"
    - "{{ playbook_dir }}/files/wofi"
  tags: [sway]

