---
- name: Install packages
  become: yes
  ansible.builtin.package:
    name: "{{ qtile_packages[ansible_os_family] }}"

- name: Install pip dependencies
  ansible.builtin.pip:
    name: "{{ qtile_pip[ansible_os_family] + qtile_pip.common }}"

- name: "Ensure desktop entry is installed"
  become: yes
  ansible.builtin.copy:
    src: qtile.desktop
    dest: /usr/share/xsessions/qtile.desktop
  when: qtile_desktop_entry 
