---

- name: Apply Debian install method
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

# TODO Handle this outside qtile role?
- name: Install other dependencies
  become: yes
  ansible.builtin.package:
    name:
      - rofi  # TODO: only x11, need wofi for wayland
      - firefox

# TODO: Arch and Fedora
