---
# NOTE: Python3 and pip is assumed installed

qtile_version: "latest"
qtile_backend: "all"  # One of: all, x11 or wayland
qtile_desktop_entry: true
qtile_extra_packages: ""
qtile_extra_pip_modules: ""

