audio_packages:
  Archlinux:
    - gst-plugin-pipewire
    - pipewire
    - pipewire-alsa
    - pipewire-jack
    - pipewire-pulse
    - wireplumber
    - sof-firmware  # TODO: This is only for intel right?
  Debian:
    - gstreamer1.0-pipewire
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - wireplumber
  Fedora:
    - pipewire
    - pipewire-alsa
    - pipewire-gstreamer
    #- pipewire-plugin-jack  # results in conflict?
    - pipewire-pulseaudio
    - wireplumber
