---
- name: "Ensure dependencies are installed"
  become: true
  ansible.builtin.package:
    name: "{{ renode_dependencies[ansible_distribution] }}"

- name: Ensure renode install directory exists
  ansible.builtin.file:
    state: directory
    mode: "0755"
    path: "{{ renode_install_dir }}"

# TODO: Might want to split this into two separate tasks to avoid downloading the archive on each invocation
- name: "Download renode v{{ renode_version }}"
  ansible.builtin.unarchive:
    src: "{{ renode_download_url }}/v{{ renode_version }}/renode-{{ renode_version }}.linux-portable.tar.gz"
    dest: "{{ renode_install_dir }}"
    remote_src: true
    extra_opts:
      - --strip-components=1
  register: download

- name: Create symbolic link for executables
  ansible.builtin.file:
    src: "{{ renode_install_dir }}/{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item }}"
    state: link
  with_items:
    - renode
    - renode-test
  when: download.changed
