---
- name: "Ensure base packages are installed"
  become: yes
  community.general.pacman:
    name:
      - base  # Includes coreutils
      - base-devel
      - git
      - linux
      - linux-firmware
      - linux-headers
      - python3
      - python3-pip
      - sudo
      - vim

- name: "Ensure x11 packages are installed"
  become: yes
  community.general.pacman:
    name:
      - xorg-xserver
      - xorg-xinit
  when: system_backend == 'x11'

- name: "Ensure services are installed"
  become: yes
  community.general.pacman:
    name:
      - networkmanager
      #- ntp
      #- firewalld  # needed? probably if avahi/openssh?
      #- sshd

- name: "Ensure services are started and enabled"
  become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - systemd-timesyncd
    - NetworkManager
    #- sshd

- name: "Ensure services are stopped and disabled"
  become: yes
  ansible.builtin.systemd:  # .service ?
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - systemd-networkd  # Replaced by NetworkManager

- name: "Ensure essential drivers are installed"
  become: yes
  command.general.pacman:
    name:
      - alsa
      - alsa-utils  # needed if alsa is installed?
      - sof-firmware  # needed?
      - mesa  # needed for? generic Video/GPU driver?
      - mesa-utils  # needed for?
      - avahi  # needed ?
      - openssh  # needed ?
      - bluez
      - bluez-utils  # needed?
      - brightnessctl

- name: "Install intel microcode if needed"
  become: yes
  community.general.pacman:
    name:
      - intel-ucode # ucode for intel cpus
      - vulkan-intel # vulkan support for intel gpu's
  when: ansible_processor[1].find('Intel') != -1

- name: "Install amd microcode if needed"
  become: yes
  community.general.pacman:
    name:
      - amd-ucode # ucode for amd
      - vulkan-radeon # vulkan support for amd gpu's
      - radeontop # radeon gpu info
  when: ansible_processor[1].find('AMD') != -1

- name: "Ensure essential tools are installed"
  become: yes
  community.general.pacman:
    name:
      - bat
      - coreutils
      - cmake
      - curl
      - glibc
      - flameshot
      - fzf
      - htop
      - inetutils  # Needed?
      - jq
      - make
      - neofetch
      - openssl
      - ripgrep
      - tar
      - valgrind
      - unzip
      - wget
      - "{{ rofi if system_backend == 'x11' else wofi }}"  # x11 or wayland

