---
- name: "base : Ensure base packages are installed"
  become: yes
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  with_items:
    - linux-firmware
    - build-essential
    - git
    - python3
    - python3-pip
    - vim

