---
- name: "Ensure base packages are installed"
  become: yes
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  with_items:
    - linux-firmware
    - build-essential  ## needed, or can this be more specific???
    - git
    - python3
    - python3-pip
    - vim

