---
- name: "Set hostname"
  become: yes
  ansible.builtin.hostname:
    name: "{{ system_hostname }}"
  when:
    - ansible_user_id != 'vagrant'  # TODO: Don't change if we're connecting to a VM?
    - system_hostname != ''

- name: "Set hostname in hosts file"
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: ^127.0.1.1
    line: '127.0.1.1        {{ system_hostname }} {{ system_hostname }}.localdomain'
  when:
    - ansible_user_id != 'vagrant'
    - system_hostname != ''

