---
- name: "pre-install : Synchronize clock via NTP"
  command: timedatectl set-ntp true

- name: "pre-install - Ensure latest keyrings are installed"
  community.general.pacman:
    update_cache: yes
    name: archlinux-keyring

- name: "pre-install : Enable pacman parallel downloads"
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: "#ParallelDownloads"
    replace: "ParallelDownloads"

- name: "pre-install : Install reflector"
  community.general.pacman:
    name: reflector

- name: "pre-install : Make backup of current mirrorlist"
  ansible.builtin.copy:
    dest: /etc/pacman.d/mirrorlist
    backup: yes

- name: "pre-install : Optimize current mirrorlist with reflector"
  command: "reflector --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist"
