---
- name: Ensure machine is booted from the Arch install media
  fail:
    msg: "This machine is not booted from the Arch install media!"
  when: ansible_nodename != 'archiso'

- name: Apply install scripts
  ansible.builtin.include_tasks: partition.yml
  with_items:
    - 01-preinstall.yml
    - partition.yml
    - encryption.yml  # when archiso_encryption_enable
    - filesystem.yml
    - btrfs.yml  # filesystem? when archiso_btrfs_enable?
    - mount.yml
    - locale.yml
    - pacstrap.yml
    - fstab.yml
    - user.yml
    - network.yml
    - audio.yml
    - drivers.yml  # network, microcode, bootloader, sshd?

- name: Reboot system
  ansible.builtin.reboot:
    connect_timeout: 1
    reboot_timeout: 1
  failed_when: false

