---
- name: Ensure machine is booted from the Arch install media
  fail:
    msg: "This machine is not booted from the Arch install media!"
  when: ansible_nodename != 'archiso'

# Can this be done with an ansible module?
- name: Synchronize clock via NTP
  command: timedatectl set-ntp true

- name: Apply partitioning
  ansible.builtin.include_tasks: partition.yml

- name: Apply encryption
  ansible.builtin.include_tasks: encryption.yml
  when: archiso_encryption_enable

- name: Apply filesystem
  ansible.builtin.include_tasks: filesystem.yml

- name: Apply btrfs
  ansible.builtin.include_tasks: btrfs.yml
  when: archiso_btrfs_enable

- name: Apply mountpoints
  ansible.builtin.include_tasks: mount.yml

- name: Apply pacstrap
  ansible.builtin.include_tasks: pacstrap.yml

- name: Apply fstab
  ansible.builtin.include_tasks: fstab.yml

# user, hostname, network, sshd, bootloader,
  #

- name: Reboot system
  ansible.builtin.reboot:
    connect_timeout: 1
    reboot_timeout: 1
  failed_when: false

