---
- name: "Wipe {{ archiso_partition_device }} and all its partitions"
  block:
    - name: "Gather {{ archiso_partition_device }} device information"
      community.general.parted:
        device: "{{ archiso_partition_device }}"
        unit: MiB
      register: device_info

    - name: "Remove all partitions from {{ archiso_partition_device }}"
      community.general.parted:
        device: "{{ archiso_partition_device }}"
        number: "{{ item.num }}"
        state: absent
      loop: "{{ device_info }}"

- name: "Create {{ partition.name }} partition"
  community.general.parted:
    device: "{{ archiso_partition_device }}"
    name: "{{ partition.name }}"
    label: "{{ partition.label }}"
    number: "{{ partition.number }}"
    part_start: "{{ partition.start }}"
    part_end: "{{ partition.end }}"
    flags: "{{ partition.flags }}"
    state: present
  loop: "{{ archiso_partitions }}"
  loop_control:
    loop_var: partition

