---
- name: "Ensure kitty and dependencies are installed"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  with_items:
    - kitty
    - "{{ kitty_dependencies }}"

- name: Copy configurations in place
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config"
  with_items: "{{ kitty_configs }}"
