---
- include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian' 

- include_tasks: install-arch.yml
  when: ansible_os_family == 'Archlinux'

- name: Ensure kitty config directory exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Copy configuration files in place
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/kitty/"
  with_items: "{{ kitty_configs }}"
