---
- name: Ensure local themes directory exists
  ansible.builtin.file:
    state: directory
    mode: "0755"
    path: "{{ ansible_user_dir }}/.themes"

- name: Install GTK themes
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.themes"
    remote_src: true
  with_items:
    - "https://github.com/EliverLara/Nordic/releases/download/v2.2.0/Nordic-darker.tar.xz"
