---
- name: Ensure local directories exist
  ansible.builtin.file:
    state: directory
    mode: "0755"
    path: "{{ ansible_user_dir }}/{{ item }}"
  with_items:
    - ".themes"
    - ".icons"

- name: Install themes
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ ansible_user_dir }}/{{ item.dest }}"
    remote_src: true
  with_items:
    - { src: "https://github.com/EliverLara/Nordic/releases/download/v2.2.0/Nordic.tar.xz", dest: ".themes" }
    - { src: "https://github.com/EliverLara/Nordic/releases/download/v2.2.0/Nordic-darker.tar.xz", dest: ".themes" }
    - { src: "https://github.com/alvatip/Nordzy-cursors/releases/download/1.0.0/Nordzy-cursors.tar.gz", dest: ".icons"}
