---
- name: Nordic | Ensure themes directory exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.themes/"
    state: directory

- name: Nordic | Download Nordic gtk theme
  ansible.builtin.unarchive:
    src: https://github.com/EliverLara/Nordic/releases/{{ themes_gtk_theme_version }}/download/Nordic.tar.xz
    dest: "{{ ansible_user_dir }}/.themes/"
    remote_src: yes
  when: themes_do_configure_gtk_theme == true

- name: Nordic | Enable Nordic gtk theme
  community.general.dconf:
    key: "{{ item.key }}"
    value: "'{{ item.value }}'"
  with_items:
    - { key: "/org/gnome/desktop/interface/gtk-theme", value: "Nordic" }
    - { key: "/org/gnome/desktop/wm/preferences/theme", value: "Nordic" }
  when: themes_do_configure_gtk_theme == true

- name: Nordic | Install Nordic Gnome terminal theme and preferences
  ansible.builtin.script: "{{ role_path }}/files/nordic-gnome-terminal.sh"

- name: Nordic | Copy desktop wallpaper in place
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nordic-wallpaper.png"
    dest: "{{ ansible_user_dir }}/.wallpaper.png"

- name: Nordic | Set desktop wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ ansible_user_dir }}/.wallpaper.png'"
