---
- name: Ensure package dependencies are installed
  become: yes
  ansible.builtin.package:
    name: "{{ waybar_packages[ansible_distribution] }}"

- name: Checkout repository
  ansible.builtin.git:
    repo: https://github.com/Alexays/Waybar.git
    depth: 1
    dest: "{{ neovim_clone_dir }}/waybar"
    version: "{{ waybar_version }}"
  register: clone

- name: Compile
  ansible.builtin.command:
    chdir: "{{ waybar_clone_dir }}/waybar"
    cmd: "{{ item }}"
  with_items:
    - "meson _build"
    - "ninja -C _build"
  register: compile

- name: Install
  become: yes
  ansible.builtin.command:
    chdir: "{{ waybar_clone_dir }}/waybar"
    cmd: "ninja -C _build install"
  when: compile.changed
