---
- name: "Ensure packages are installed"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
  loop: "{{ service_packages }}"

- name: "Configure service"
  block:
    - name: "Ensure {{ service_name }} is {{ 'enabled' if service_enabled else 'disabled' }}"
      become: yes
      ansible.builtin.service:
        name: "{{ service_name }}"
        enabled: "{{ service_enabled }}"
    
    - name: "Ensure {{ service_name }} is {{ service_state }}"
      become: yes
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
  when: service_name is defined

