---
- name: "Ensure build dependencies are installed"
  become: yes
  ansible.builtin.package:
    name: "{{ quickemu_dependencies[ansible_distribution] }}"

- name: Checkout repository
  ansible.builtin.git:
    repo: https://github.com/wimpysworld/quickemu
    depth: 1
    dest: "{{ quickemu_clone_dir }}/quickemu"
    version: "{{ quickemu_version }}"
  register: clone

- name: Create symbolic link for executables
  ansible.builtin.file:
    src: "{{ quickemu_clone_dir }}/quickemu/{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item }}"
    state: link
  with_items:
    - quickemu
    - quickget
  when: clone.changed
