---
- name: Ensure dependencies are installed
  become: yes
  ansible.builtin.package:
    name: "{{ neovim_build_dependencies[ansible_distribution] }}"
    state: present

- name: Checkout repository
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    depth: 1
    dest: "{{ neovim_clone_dir }}/neovim"
    version: "{{ neovim_version }}"
  register: clone

- name: Compile
  community.general.make:
    chdir: "{{ neovim_clone_dir }}/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
      CMAKE_INSTALL_PREFIX: "{{ ansible_user_dir }}/.local"
  register: compile
  when: clone.changed

- name: Install
  community.general.make:
    chdir: "{{ neovim_clone_dir }}/neovim"
    target: "install"
  when: compile.changed
