eww_packages: {
    Fedora: [
      gtk3-devel,
      pango-devel,
      cairo-devel,
      cairo-gobject-devel,
      glib2-devel,
      glibc-devel,
      libgcc,
      rust-gdk-devel,
      gdk-pixbuf2-devel,
      gtk-layer-shell-devel,  # only on wayland
    ]
  }
